name: Mergability check for GitHub Merge Queue
on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  testing:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on:
      ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Run Gradle test task
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            test
            --full-stacktrace
            --no-build-cache
      - name: compress test reports
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          tar -czvf test-report.tar.gz app/build/reports/*
      - name: upload test report
        if: ${{ matrix.os }} == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.tar.gz
  building:
    needs:
      - testing
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    if: ${{ success() }} && github.event_name == 'merge_group'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Run Gradle build task
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            jpackageImage
            -i
            --scan
            --no-build-cache
            --refresh-dependencies
