name: Mergability check for GitHub Merge Queue
on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  testing:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on:
      ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run Gradle test task
        uses: gradle/gradle-build-action@v1
        with:
          arguments: |
            test
            -i
            --build-cache
            --scan
            --configure-on-demand
  building:
    needs:
      - testing
    runs-on: ${{ matrix.os }}
    if: ${{ success() }} && github.event_name == 'merge_group'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run Gradle build task
        uses: gradle/gradle-build-action@v1
        with:
          arguments: |
            jpackageImage
            -i
            --scan
            --build-cache
            --configure-on-demand
            --refresh-dependencies
