name: Mergability check for GitHub Merge Queue
on:
  merge_group:
    branches:
        - main

concurrency:
  group: merge-queue
  cancel-in-progress: false

jobs:
  building:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run Gradle build task
        uses: gradle/gradle-build-action@v1
        with:
          arguments: |
            jpackageImage
            -i
            --scan
            --build-cache
            --configure-on-demand
            --configuration-cache
            --refresh-dependencies
